---
- name: Ensure iptables is installed.
  apt:
    name: iptables
    state: present

- name: Ensure iptables-persistent is installed.
  apt:
    name: iptables-persistent
    state: present

- name: Ensure if netfilter-persistent is present
  shell: which netfilter-persistent
  register: firewall_netfilter_present
  changed_when: False
  ignore_errors: yes

- name: Define command to persist the rules
  set_fact:
    firewall_persist_command: netfilter-persistent save
  when: firewall_netfilter_present.rc == 0

- name: Define command to persist the rules
  set_fact:
    firewall_persist_command: /etc/init.d/iptables-persistent save
  when: firewall_netfilter_present.rc == 1
